# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to csharp_port
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: release
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          
      - name: Publish
        run: dotnet publish Bot.Main/Bot.Main.csproj -c release -f net6.0 -o published
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts       
        
      - name: Deploy with rsync
        run: rsync -avz published/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/botc_bin/
        
      #- name: Run the 'new deploy' script on the server
      #  uses: fifsky/ssh-action@master
      #  with:
      #    command: |
      #      cd /usr/botc
      #      nohup ./new-deploy.sh
      #    host: ${{ secrets.SSH_HOST }}
      #    user: ${{ secrets.SSH_USER }}
      #    key: ${{ secrets.SSH_PRIVATE_KEY }}
      #    args: -tt

